name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: login in ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g8t1r9s1

    - name: Build, tag & push the Docker image
      run: |
        docker build . -t alintoma/serve-image
        docker tag alintoma/serve-image:latest public.ecr.aws/g8t1r9s1/alintoma/serve-image:latest
        docker push public.ecr.aws/g8t1r9s1/alintoma/serve-image:latest
